#!/bin/sh
# This document is intended to test out different style changes on
# Mallard documents. If you need to test things not in this document,
# feel free to add stuff to this document. You can use lipsum.com
# to generate text.
#
# To try things out, just make changes directly to the files in your
# checkout of yelp-xsl. You don't have to build or install your copy
# of yelp-xsl. Just build this preview document. To build this preview
# document, just run this README. You do need yelp-tools installed
# for the yelp-build command. It's in your distro's packages, and you
# might have it installed already anyway.
#
# ./README

yelp-build cache *.page
if [ ! -d html ]; then mkdir html; fi
cp ../../js/highlight.pack.js html/
for page in *.page; do
    xsltproc \
        --stringparam mal.cache.file index.cache \
        -o html/ \
        ../../xslt/mallard/html/mal2html.xsl \
        $page;
done
rm index.cache
